<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DCNchA0' shared service.

return $this->privates['.service_locator.DCNchA0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\PanierController::ajouter' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\PanierController::supprimerArticle' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\ProductController::show' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
    'App\\Controller\\PanierController:ajouter' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\PanierController:supprimerArticle' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\ProductController:show' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
));
