<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\vendor\\easycorp\\easyadmin-bundle\\src\\Controller\\AdminControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\easycorp\\easyadmin-bundle\\src\\Controller\\EasyAdminController.php';

$this->services['EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController'] = $instance = new \EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController();

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'doctrine' => array('services', 'doctrine', 'getDoctrineService', false),
    'easyadmin.autocomplete' => array('services', 'easyadmin.autocomplete', 'getEasyadmin_AutocompleteService.php', true),
    'easyadmin.config.manager' => array('services', 'easyadmin.config.manager', 'getEasyadmin_Config_ManagerService', false),
    'easyadmin.paginator' => array('services', 'easyadmin.paginator', 'getEasyadmin_PaginatorService.php', true),
    'easyadmin.property_accessor' => array('services', 'easyadmin.property_accessor', 'getEasyadmin_PropertyAccessorService', false),
    'easyadmin.query_builder' => array('services', 'easyadmin.query_builder', 'getEasyadmin_QueryBuilderService.php', true),
    'event_dispatcher' => array('services', 'event_dispatcher', 'getEventDispatcherService', false),
    'form.factory' => array('services', 'form.factory', 'getForm_FactoryService.php', true),
    'http_kernel' => array('services', 'http_kernel', 'getHttpKernelService', false),
    'parameter_bag' => array('privates', 'parameter_bag', 'getParameterBagService', false),
    'request_stack' => array('services', 'request_stack', 'getRequestStackService', false),
    'router' => array('services', 'router', 'getRouterService', false),
    'security.authorization_checker' => array('services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false),
    'security.csrf.token_manager' => array('services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService.php', true),
    'security.token_storage' => array('services', 'security.token_storage', 'getSecurity_TokenStorageService', false),
    'serializer' => array('services', 'serializer', 'getSerializerService.php', true),
    'session' => array('services', 'session', 'getSessionService.php', true),
    'twig' => array('services', 'twig', 'getTwigService', false),
)))->withContext('EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController', $this));

return $instance;
