version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: catalogue
            MYSQL_USER: catalogue
            MYSQL_PASSWORD: catalogue
    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./catalogue:/var/www/catalogue:cached
            - ./logs/catalogue:/var/www/catalogue/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
