version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/catalogue:cached
      - ./logs/catalogue:/var/www/catalogue/var/logs:cached
    links:
      - postgres
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached