<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\PanierController::ajouter' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\PanierController::supprimerArticle' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\ProductController::index' => array('privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true),
    'App\\Controller\\ProductController::show' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
    'App\\Controller\\PanierController:ajouter' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\PanierController:supprimerArticle' => array('privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true),
    'App\\Controller\\ProductController:index' => array('privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true),
    'App\\Controller\\ProductController:show' => array('privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
