<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfEGvXq\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfEGvXq/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLfEGvXq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLfEGvXq\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerLfEGvXq\srcApp_KernelTestDebugContainer(array(
    'container.build_hash' => 'LfEGvXq',
    'container.build_id' => '76c396d5',
    'container.build_time' => 1548522341,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfEGvXq');
