<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxZ1ZDx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxZ1ZDx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxZ1ZDx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxZ1ZDx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLxZ1ZDx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'LxZ1ZDx',
    'container.build_id' => '87691109',
    'container.build_time' => 1548601146,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxZ1ZDx');
